//! Auto-write the auth file on first run.
//!
//! When `~/pristine-auth.toml` (or the path supplied via `--auth`) is absent,
//! `ensure_auth_file` writes a hardcoded template containing an
//! `AnthropicProvider` section and a `default` model alias referencing the
//! `{{ANTHROPIC_API_KEY}}` placeholder. The write is atomic — content is
//! staged at `<path>.tmp` and then renamed onto the target — and the final
//! file is chmod 600 on Unix so the embedded api-key placeholder (and any
//! credential the user later substitutes for it) is not world-readable.
//!
//! Existing files are left untouched: `ensure_auth_file` returns `Ok(false)`
//! without inspecting the contents. The template is verified to round-trip
//! through `AuthConfig` deserialization by a unit test in this module.

use std::fs;
use std::path::Path;

use crate::config::error::ConfigError;

/// Default contents written when the auth file is absent. Edited by the user
/// on first run; the `api_key` placeholder is resolved by the templating layer
/// once `ANTHROPIC_API_KEY` is set in the environment.
const TEMPLATE: &str = "# Auto-generated by pristine on first run. Edit to taste.
#
# Provider definitions. v1 ships AnthropicProvider as the only valid type.

[providers.anthropic]
type = \"anthropic\"
# Uncomment to override the default API endpoint:
# base_url = \"https://api.anthropic.com\"

# Model aliases. Topology files reference these by name (e.g. model = \"default\").

[models.default]
provider = \"anthropic\"
model_name = \"claude-opus-4-7\"
api_key = \"{{ANTHROPIC_API_KEY}}\"

[models.fable]
provider = \"anthropic\"
model_name = \"claude-fable-5\"
api_key = \"{{ANTHROPIC_API_KEY}}\"
";

/// If `path` already exists, return `Ok(false)`. Otherwise create any missing
/// parent directories, write the template to `<path>.tmp`, chmod the temp
/// file to `0o600` on Unix, rename it onto `path`, and return `Ok(true)`.
///
/// Rationale for chmod-on-tmp-then-rename: the rename is atomic, so a reader
/// either sees no file at all or sees the final file with its final mode.
/// Setting the mode on the temp path before the rename closes the window
/// where the final file would briefly carry the umask-derived default.
pub fn ensure_auth_file(path: &Path) -> Result<bool, ConfigError> {
    if path.exists() {
        return Ok(false);
    }

    if let Some(parent) = path.parent()
        && !parent.as_os_str().is_empty()
    {
        fs::create_dir_all(parent).map_err(|source| ConfigError::IoError {
            path: parent.to_path_buf(),
            source,
        })?;
    }

    let mut tmp_os = path.as_os_str().to_owned();
    tmp_os.push(".tmp");
    let tmp = std::path::PathBuf::from(tmp_os);

    fs::write(&tmp, TEMPLATE).map_err(|source| ConfigError::IoError {
        path: tmp.clone(),
        source,
    })?;

    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        let perms = fs::Permissions::from_mode(0o600);
        fs::set_permissions(&tmp, perms).map_err(|source| ConfigError::IoError {
            path: tmp.clone(),
            source,
        })?;
    }

    fs::rename(&tmp, path).map_err(|source| ConfigError::IoError {
        path: path.to_path_buf(),
        source,
    })?;

    Ok(true)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::config::auth::{AuthConfig, ProviderConfig};
    use tempfile::tempdir;

    #[test]
    fn template_parses_as_auth_config() {
        let cfg: AuthConfig =
            toml::from_str(TEMPLATE).expect("hardcoded template must parse as AuthConfig");
        assert_eq!(cfg.providers.len(), 1);
        let provider = cfg
            .providers
            .get("anthropic")
            .expect("anthropic provider present");
        match provider {
            ProviderConfig::Anthropic { base_url } => assert!(base_url.is_none()),
        }
        assert_eq!(cfg.models.len(), 2);
        let model = cfg.models.get("default").expect("default model present");
        assert_eq!(model.provider, "anthropic");
        assert_eq!(model.model_name, "claude-opus-4-7");
        assert_eq!(model.api_key, "{{ANTHROPIC_API_KEY}}");
        let fable = cfg.models.get("fable").expect("fable model present");
        assert_eq!(fable.provider, "anthropic");
        assert_eq!(fable.model_name, "claude-fable-5");
        assert_eq!(fable.api_key, "{{ANTHROPIC_API_KEY}}");
    }

    #[test]
    fn existing_file_is_left_alone() {
        let dir = tempdir().expect("tempdir");
        let path = dir.path().join("pristine-auth.toml");
        let sentinel = "sentinel = \"do not touch\"\n";
        fs::write(&path, sentinel).expect("pre-write sentinel");

        let wrote = ensure_auth_file(&path).expect("existing file path succeeds");
        assert!(
            !wrote,
            "ensure_auth_file should not overwrite existing file"
        );

        let on_disk = fs::read_to_string(&path).expect("read back sentinel");
        assert_eq!(on_disk, sentinel);
    }

    #[test]
    fn missing_file_is_written_with_template() {
        let dir = tempdir().expect("tempdir");
        let path = dir.path().join("pristine-auth.toml");

        let wrote = ensure_auth_file(&path).expect("missing file path succeeds");
        assert!(wrote, "ensure_auth_file should write missing file");

        let on_disk = fs::read_to_string(&path).expect("read back template");
        assert_eq!(on_disk, TEMPLATE);
    }

    #[cfg(unix)]
    #[test]
    fn missing_file_is_chmod_600_on_unix() {
        use std::os::unix::fs::PermissionsExt;

        let dir = tempdir().expect("tempdir");
        let path = dir.path().join("pristine-auth.toml");

        let wrote = ensure_auth_file(&path).expect("missing file path succeeds");
        assert!(wrote);

        let meta = fs::metadata(&path).expect("metadata on written file");
        let mode = meta.permissions().mode() & 0o777;
        assert_eq!(mode, 0o600, "file mode should be 0o600, got {mode:o}");
    }

    #[test]
    fn parent_directory_is_created() {
        let dir = tempdir().expect("tempdir");
        let nested = dir.path().join("nested").join("dir");
        let path = nested.join("pristine-auth.toml");
        assert!(!nested.exists(), "precondition: nested dir does not exist");

        let wrote = ensure_auth_file(&path).expect("nested path succeeds");
        assert!(wrote);
        assert!(nested.is_dir(), "parent directory should be created");
        assert!(path.is_file(), "auth file should be written");
    }

    /// Triggering an IoError reliably across platforms is awkward; we use the
    /// Unix-only trick of placing a regular file where `create_dir_all` wants
    /// to put a directory, which forces a clear `ErrorKind::NotADirectory`
    /// (or `AlreadyExists` on some kernels) from `create_dir_all`.
    #[cfg(unix)]
    #[test]
    fn io_error_path_is_propagated() -> Result<(), Box<dyn std::error::Error>> {
        let dir = tempdir().expect("tempdir");
        let blocking_file = dir.path().join("blocker");
        fs::write(&blocking_file, b"i am a file, not a directory").expect("write blocker");
        let path = blocking_file.join("pristine-auth.toml");

        let err = ensure_auth_file(&path).expect_err("blocked path should error");
        match err {
            ConfigError::IoError { path: err_path, .. } => {
                assert_eq!(
                    err_path, blocking_file,
                    "IoError should carry the path that failed (the blocking parent)"
                );
            }
            other => return Err(format!("expected ConfigError::IoError, got {other:?}").into()),
        }
        Ok(())
    }
}
